"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""


def sumevenfib2n(n):
    le = 2  # last even
    lo = 1  # last odd
    ne = le
    run_sum = le if n > 2 else 0  # track running sum here
    while ne < n:
        o1 = lo + le
        o2 = o1 + le
        ne = o1 + o2
        run_sum += ne
        lo = o2
        le = ne
    return run_sum - ne

if __name__ == "__main__":
    print(sumevenfib2n(4000000))
