"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""

class EvenFibNumber:
    def __init__(self):
        self.lo = 1
        self.le = 2
        self.ne = self.le
    
    def __iter__(self):
        return self
        
    def next(self):
        o1 = self.le + self.lo
        o2 = self.le + o1
        self.ne = o1 + o2
        self.le = self.ne
        self.lo = o2
        return self.ne

def sumevenfib2n(n):
    g = EvenFibNumber()
    run_sum = g.ne
    
    for i in g:
        if i < n:
            run_sum += i
        else:
            break
    return run_sum

if __name__ == "__main__":
    print(sumevenfib2n(4000000))